# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install build dependencies
      run: sudo apt-get -qq update && sudo apt-get install --no-install-recommends -y bash jq
    - name: Checkout
      uses: actions/checkout@v6
    - name: Use Node.js LTS
      uses: actions/setup-node@v6
      with:
        node-version: lts/*
        check-latest: true
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Lint
      run: npm run lint
    - name: Test
      run: npx nyc --reporter=lcov npm test
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v7
      with:
        fail_ci_if_error: true
        verbose: true
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
