name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        command:
          - firefox
          - chrome
    steps:
      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install -y bash inkscape jq
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - name: Submit
        run: |
          case ${{ matrix.command }} in
            chrome)
              npx chrome-webstore-upload-cli upload --auto-publish --source web-ext-artifacts/chrome/*.zip
              ;;
            firefox)
              npx web-ext-submit --artifacts-dir web-ext-artifacts/firefox
              ;;
          esac
        env:
          EXTENSION_ID: ${{ secrets.CHROME_EXTENSION_ID }}
          CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
          REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}
          WEB_EXT_API_KEY: ${{ secrets.AMO_API_KEY }}
          WEB_EXT_API_SECRET: ${{ secrets.AMO_API_SECRET }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            web-ext-artifacts/**/.zip
            web-ext-artifacts/**/.xpi
